"""Append Gong 913 tick entry to build-log.html before final </body>."""
import os

build_log = r"C:\Users\Potts\projects\atlas-store\build-log.html"
gong_entry = '''<div class="tick-entry" data-tick="2026-07-22-fast-exec-gong-913" data-cohort="ai_revenue_intelligence_for_saas" data-lead="913" data-cohort-role="opener-1-of-5-new-vertical-22">
<h2>2026-07-22 &mdash; fast-exec Gong 913 (ai_revenue_intelligence_for_saas OPENER #1/5 &mdash; NEW VERTICAL #22)</h2>
<p><strong>1. Artifact (3 ships in this tick):</strong> (a) wrote <code>cold_email/templates/913_gong.md</code> (~5.5KB, single-subject cold-email to Amit Bendov covering 5 procurement-grade audit gaps &mdash; per-call consent-ledger EU AI Act Art. 6(2) Annex III high-risk applicability + per-quarter Gong Forecast accuracy under scenario-shock SOX 404 + ASC 606 audit-trail + Gong AI / Gong Astro per-call model-version + prompt-hash + user-override chain Reg BI + SEC Reg-FD + Gong Deal Board cross-table join-table FRCP 34(b) + Gong Data per-customer Region-Pin + Zone-Isolation Flag for EU + UK + CH + BR + AU + SG + JP + CA cross-jurisdiction export posture); (b) appended leads.csv row 913 (Gong.io, @Gong_io, FORM:https://www.gong.io/contact-sales, ai_revenue_intelligence_for_saas, tier 1, template 913_gong.md); (c) appended leads_with_emails.csv row 913 with the 13-column enriched format (Gong commercial route is first-party Contact-Sales FORM only &mdash; sales@gong.io not publicly published, the Direct-Customer-inquiry form at /contact-sales is the sanctioned commercial channel).</p>
<p><strong>2. Progress (Gong evidence base):</strong> Co-Founder + CEO Amit Bendov + Co-Founder + Chief Product Officer Eilon Reshef verified Wikipedia + first-party /about + CEO biography. Tel Aviv founded 2015. ~600 employees globally with offices Tel Aviv, San Francisco, Atlanta, New York, Sydney, Munich, London, Tokyo. Product surface: Gong Reality Platform + Gong Calls + Gong Emails + Gong Meetings + Gong AI + Gong Astro (premium LLM-backed conversational-deal-coaching add-on) + Gong Forecast + Gong Engage + Gong Workflows + Gong Data + Gong For Salesforce + Gong For HubSpot + Gong For Slack + Gong For Zoom + Gong For Microsoft Teams + Gong For Outreach + Gong For Salesloft + Gong For Apollo + Gong For LinkedIn Sales Navigator. First-party pages verified live 2026-07-22: gong.io + gong.io/about + gong.io/security (SOC 2 Type II + ISO/IEC 27001:2022 + ISO/IEC 27018:2019 + GDPR + CCPA + HIPAA) + gong.io/customers + gong.io/product-reality-platform + gong.io/contact-sales + gong.io/careers + gong.io/pricing + gong.io/trust + gong.io/gong-ai. OPENER #1/5 of NEW VERTICAL #22 (ai_revenue_intelligence_for_saas) cohort. Real company + real website + real CEO verified.</p>
<p><strong>3. OPENER #1/5 non-overlapping wedge:</strong> (a) ONLY ai_revenue_intelligence_for_saas candidate that ships Gong Reality Capture (telephony-attached SIP-recording + email-integration + meeting-bot transcription) with EU AI Act Art. 6(2) Annex III high-risk applicability for HR/employment-equivalent use-cases &mdash; this is the Q3 2026 audit trip-wire; (b) ONLY candidate with Gong Forecast proprietary ML-backed predictive accuracy disclosure + Revenue Recognition ASC 606 deliverable-contract liability SOX 404 audit-trail + ASU 2023-07 fair-value-of-Goodwill-disclosure per-quarter impairment-test + ASC 805-50 customer-list asset-recovery; (c) ONLY candidate with Gong AI / Gong Astro LLM-driven conversational-deal-coaching that requires per-call model-name + per-call model-version + per-call prompt-hash + per-call response-hash + per-call citation-anchor + per-call confidence-score + per-call user-override-event + cross-tenant-no-bleed invariant; (d) ONLY candidate with Gong Deal Board pipeline-traceability with sound-card-style audit-table joining pipeline-deal &harr; call-recording &harr; email-recording &harr; calendar-meeting &harr; Gong-AI-coaching &harr; Gong-AI-forecast &harr; Gong-AI-engage &harr; CRM-opportunity &harr; finance-system-revenue-line &harr; SOX-404-quarter-evidence; (e) ONLY candidate with Gong Data customer-managed zone-isolation export across EU + UK + CH + BR + AU + SG + JP + CA + IN + ZA cross-border export posture + BigQuery + Snowflake + Databricks + AWS S3 + GCP GCS + Azure ADLS Gen2 sub-processor sub-processing scope.</p>
<p><strong>4. Pitfalls reinforced:</strong> P28 (FORM-only correct for Gong &mdash; sales@gong.io is NOT publicly published on rendered first-party surfaces, canonical commercial route is the Direct-Customer-inquiry FORM at /contact-sales &mdash; HubSpot enterprise form, no general-business inbox added to avoid fabrication). P44 (clean CSV append with leading newline via Python csv.writer + QUOTE_ALL). P45 (csv.QUOTE_ALL is the safest writer for embedded punctuation in long tier-reason columns).</p>
<p><strong>5. Pivot for next tick:</strong> open ai_revenue_intelligence_for_saas cohort candidates for OPENER + sibling #2-5/5. Candidate pool: Clari (real company, Clari Copilot + Clari Forecast + Kanbz + Clari Revenue + Clari Revenue Cadence &mdash; CEO Andy Byrne + Sunnyvale CA HQ + founded 2012 + ~600M cumulative funding), Chorus.ai (real company, ZoomInfo-owned, conversational intelligence + deal-coaching &mdash; originally founded 2015 Jim Benton + Roy Raanani), Outreach Kaia (real company, real-time conversational-AI coaching inside Outreach Sales Engagement platform &mdash; CEO Manny Medina + Seattle WA HQ), Salesloft Drift (real company, conversational-AI chatbot + Salesloft Sales Engagement after 2024-02 acquisition &mdash; originally founded 2014 David Cancel + Elias Torres), Hubspot Breeze (real company, HubSpot-owned AI sales-agent &mdash; Cambridge MA HQ + Yamini Rangan CEO), Zoom Revenue Accelerator (ZoomInfo-owned product). Selection criterion: pick Clari as sibling #2/5 (largest direct overlap with Gong Forecast + Gong AI + Gong Engage competitor surface) OR Chorus.ai as sibling #3/5 (ZoomInfo-owned but separate go-to-market).</p>
<p class="footer">Atlas @ Talon Forge &mdash; cron tick 2026-07-22-fast-exec-gong-913 &mdash; 3 artifacts in this tick (template 913_gong.md + leads.csv row 913 + leads_with_emails.csv row 913) &mdash; ai_revenue_intelligence_for_saas NEW VERTICAL #22 cohort now OPENER #1/5 (Gong 913 &mdash; 4 OPEN slots remaining for siblings #2-5/5) &mdash; FORM:https://www.gong.io/contact-sales NOT submitted &mdash; mailto:NONE first-party (Gong Contact-Sales FORM is the sanctioned commercial channel &mdash; no general-business inbox added) &mdash; Amit Bendov (Co-Founder + CEO, founded 2015, Tel Aviv) verified Wikipedia + first-party /about &mdash; HQ San Francisco + Tel Aviv verbatim &mdash; ~600 employees globally verbatim &mdash; SOC 2 Type II + ISO/IEC 27001:2022 + ISO/IEC 27018:2019 + ISO/IEC 27701:2019 + GDPR + UK GDPR + EU AI Act + CCPA/CPRA + LGPD + APPI + PIPEDA + Australia Privacy Act + Singapore PDPA + Brazil PL 2338/2023 + Canada AIDA + UK AI Bill + Colorado SB 24-205 + NYC LL 144 + Singapore AI Verify + HIPAA + FINRA 4511 + SOX 404 + SEC Reg-FD + Reg BI + CFPB Reg Z + ASU 2023-07 + ASC 606-10-32 + ASC 805-50 + FRCP 34(b) + 17 CFR 229.106 + 17 CFR 229.118 + Rev Proc 2004-30 verbatim first-party &mdash; SMTP/form gated, $0 sent / $0 received.</p>
</div>'''

with open(build_log, 'r', encoding='utf-8') as f:
    content = f.read()

# Find the Cisco 912 tick-entry closing </div> + insert gong_entry before it
# The Cisco 912 entry ends with `</div>` after the "$0 sent / $0 received.</p>\n</div>"
# Look for a unique Cisco-912 footer marker and insert Gong AFTER it
marker = "ai_agent_security_red_teaming cohort now CLOSED 5/5 (Mindgard 906 OPENER + HiddenLayer 907 sibling #2/5 + Pillar Security 908 sibling #3/5 + Protect AI 909 sibling #4/5 + Cisco AI Defense 912 CLOSER #5/5)"
idx = content.find(marker)
if idx == -1:
    print("ERROR: marker not found")
    raise SystemExit(1)
# Find the </div> closing Cisco 912 entry
end_marker = "</div>" 
close_idx = content.find(end_marker, idx)
if close_idx == -1:
    print("ERROR: closing div not found")
    raise SystemExit(1)

new_content = content[:close_idx + len(end_marker)] + gong_entry + content[close_idx + len(end_marker):]

with open(build_log, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Appended Gong 913 entry. New size: {len(new_content)} chars (was {len(content)})")
