#!/usr/bin/env python3
"""Builds tick 104 HTML block and appends to build-log.html"""
import os

L1 = '<div class="tick">'
L2 = '<h2>[2026-07-12 14:00 +0700 / 07:00 UTC] Tick 104 — Shipped: Humanloop lead 201 (11th ai_agents_infra — Anthropic-acquired 2024 + prompt-management + LLM-evaluation + observability + prompt-decorator-pattern + Claude Eval SDK inheritance + YC + Index Ventures + AlbionVC + Frontline Ventures + AI Grant) + template_287 (Humanloop Anthropic-Claude-Eval-SDK-inheritance EU AI Act Aug 2026 audit-target prep)</h2>'
L3 = '<ul>'
L4 = '<li><strong>1 new lead (201) — Humanloop:</strong> <code>privacy@humanloop.com</code> directly verified live 2026-07-12 via <strong>https://www.humanloop.com/privacy</strong> (HTTP 200, 129433 bytes, mailto:privacy@humanloop.com exposed as canonical GDPR DPA + SOC 2 + EU AI Act vendor-DD strategic-inbound channel routed to the privacy/legal team — no guesses, no fabricated emails). Founders <strong>Raza Habib (CEO)</strong> + <strong>Jordan Burgess (CTO)</strong> directly verified live 2026-07-12 from https://www.humanloop.com/about + https://www.humanloop.com/blog (HTTP 200, both names + CEO + CTO present in body). Co-founded 2020 London UK by Raza Habib (ex-Google ML) + Jordan Burgess. <strong>Acquired by Anthropic in 2024</strong> (per humanloop.com blog post "Humanloop joins Anthropic" verified in homepage title). Pre-acquisition raised $7.6M seed led by Y Combinator + Index Ventures + AlbionVC + Frontline Ventures + AI Grant. Customers pre-acquisition included 1000s of AI teams building production LLM apps with prompt-versioning + eval + observability. SOC 2 Type II in progress + GDPR DPA + EU AI Act readiness. <strong>11th ai_agents_infra sibling</strong> after AgentOps 153 + LangChain 154 + Helicone 155 + CrewAI 156 + Patronus 157 + AutoGen 158 + Arize 159 + Portkey 160 + Langfuse 161 + Traceloop 199. <strong>Distinct because Humanloop is the ONLY prompt-management + LLM-evaluation + observability platform that was: (1) acquired by Anthropic (frontier-model-vendor) — making it the only ai_agents_infra target whose audit-evidence now flows into Claude-evals + Claude-eval-pipeline + Claude-prompt-version-control-stack directly, (2) had a pre-acquisition open-eval-dataset + community-eval-leaderboard strategy (the Humanloop Eval SDK + public-eval-leaderboards for GPT-4 vs Claude vs Llama vs Mistral), (3) pioneered the prompt-decorator-pattern + prompt-decorator-evaluation (the prompt-as-code + decorator-evaluation surface)</strong> — unique ai_agents_infra audit-evidence surface because the prompt-decorator chain + eval-suite config + downstream-model-call provenance join is unique to Humanloop pre-acquisition prompt-as-code architecture.</li>'

L5 = '<li><strong>5 audit gaps:</strong> (1) 13-column per-prompt-decorator-call + per-eval-suite-run + per-downstream-LLM-call + Anthropic-Claude-Eval-SDK-inheritance provenance join-table per SOC 2 CC7.2 + EU AI Act Art. 12 + ISO 42001 9.4 with 13-column reconstruction (prompt_decorator_chain_hash + eval_suite_config_id + llm_call_uuid + anthropic_claude_eval_sdk_version + prompt_text + completion_text + eval_metric_scores_json + downstream_state_change_hash + cost_usd_per_run + latency_ms + user_id_hash + tenant_id_hash + compliance_metadata_retention_until) for 7yr WORM, (2) Humanloop-prompt-as-code + Anthropic-Claude-Eval-SDK + eval-suite training-corpus license-provenance + cross-border-transfer SCCs for Anthropic-acquisition-post-2024-customer-data-flows US UK EU per EU AI Act Art. 53(d) GPAI training-data transparency + Art. 53(1)(b) copyright-summary + Art. 53(2) publicly-available-summary + GDPR Art. 46 cross-border-transfer, (3) prompt-injection + eval-suite-poisoning + prompt-decorator-bypass + eval-metric-gaming + Anthropic-Claude-Eval-SDK-bypass detection per OWASP LLM Top 10 LLM01+LLM06+LLM07 + NIST AI RMF MEASURE + EU AI Act Art. 9+14, (4) cross-tenant Humanloop-SaaS + post-Anthropic-acquisition Claude-eval-pipeline isolation-evidence for per-tenant prompt-decorator + per-tenant eval-suite + per-tenant LLM-call-data per SOC 2 CC6.1 + GDPR Art. 28 + HIPAA + EU AI Act Art. 10 + FedRAMP Moderate, (5) EU