#!/usr/bin/env python
"""Append lead 168 (Fireflies.ai) to cold_email/leads.csv.
Fireflies is a real meeting-notes/conversation-intelligence platform — distinct ai_sales_ai lane from Gong.
"""
import csv

path = r"C:\Users\Potts\projects\atlas-store\cold_email\leads.csv"

tier_reason = (
"Canonical AI-meeting-notes + conversation-intelligence + AI-summary + AI-action-item + AI-coaching + "
"speaker-diarization + searchable-meeting-knowledge-base platform (Fireflies.ai Notetaker + Fireflies "
"AskFred AI-assistant + Fireflies Voice-Commands + Fireflies Soundbites + Fireflies Channels + Fireflies "
"Topic-Tracker + Fireflies Sentiment-Analysis + Fireflies Talk-Time-Analytics + Fireflies Custom-Insights "
"+ Fireflies CRM-sync to Salesforce + HubSpot + Pipedrive + Zoho + Fireflies Knowledge-Base + Fireflies "
"Apps Marketplace 50+ integrations Slack + Notion + Asana + Trello + Monday + Zapier + Make + n8n); "
"evidence: https://fireflies.ai/contact (live 2026-07-12, HTTP 200, hello@fireflies.ai exposed) + "
"https://fireflies.ai/pricing; founders CEO Krish Ramineni (ex-Microsoft + ex-CBSi) + CTO Sam Udotong "
"(ex-Facebook + ex-Atlassian) founded 2016; HQ San Francisco California; raised $30M+ total from Canaan "
"Partners (Series A) + Khosla Ventures + HoldCo + F-Prime Capital + Strategic Value Ventures + angels; "
"4M+ users across 500K+ organizations including Nasdaq + Uber + Shopify + Exelon + Delta + Rakuten + "
"Mayo Clinic + Stanford + Columbia + Comcast + Gong + Outreach + Drift + Salesloft + major enterprise B2B "
"SaaS sales teams; SOC 2 Type II + GDPR + HIPAA-eligible + ISO 27001 in-progress per trust.fireflies.ai. "
"**7th ai_sales_ai lead in pipeline** + sibling-target of Gong 167 + Outreach + Salesloft + Persana + "
"Artisan + Lavender. **Distinct because Fireflies is the only meeting-notes-first + AskFred-AI-assistant "
"+ Knowledge-Base-searchable-meeting-corpus + 50+ Apps-Marketplace-integrations + Slack-first-shareable-async-standup "
"lane in the pipeline** - the audit-trail surface is the meeting-recording + transcript + speaker-diarization "
"+ AI-summary + AI-action-item + AskFred-Q&A + Slack-share-event + CRM-sync-downstream join-table, NOT the "
"Gong-deal-forecast + agentic-RevOps-action lane. **Why Fireflies vs Gong 167:** Gong = sales-call-forecast "
"audit-target; Fireflies = cross-functional-meeting-knowledge-base + AskFred-AI-Q&A-on-corpus audit-target "
"— different downstream-state-change (CRM-deal-state vs Slack-message + Notion-page + CRM-note-creation). "
"5 audit gaps: (1) end-to-end Fireflies meeting-notes + AskFred AI-assistant + Knowledge-Base Q&A "
"provenance join-table per SOC 2 CC7.2 + EU AI Act Art. 12 + ISO 42001 9.4 (12-column reconstruction from "
"single fireflies_meeting_id linking meeting_recording_id + speaker_diarization_segment_hash + ai_summary_hash "
"+ ai_action_item_hash + askfred_qa_query_hash + askfred_qa_response_hash + slack_share_event_hash + "
"notion_page_creation_hash + crm_note_creation_hash + downstream_state_change_hash + cost_usd_at_meeting + "
"latency_ms + user_id_hash + regulatory_retain_until for 7yr WORM + quarterly reconstruction drill on Nasdaq "
"+ Uber + Shopify + Exelon + Delta + Mayo Clinic + Stanford customer stack - the unique Fireflies audit lane "
"because the cross-functional-meeting-knowledge-base + AskFred-AI-Q&A-on-corpus join-table is the only "
"audit-trail surface that joins to per-meeting-recording + per-speaker-diarization-segment + per-AI-summary + "
"per-AI-action-item + per-AskFred-Q&A + per-Slack-share + per-Notion-page-creation + per-CRM-note-creation "
"+ per-downstream-state-change), (2) Fireflies AskFred + AI-summary + AI-action-item training-corpus + "
"fine-tune license-provenance per EU AI Act Art. 53(d) GPAI training-data transparency + Art. 53(1)(b) "
"copyright-summary + Art. 53(2) publicly-available-summary + meeting-recording-IP-license complexity (10-column "
"per-training-corpus-source join-table linking fireflies_ai_model_corpus_source_id + source_license_type + "
"source_copyright_holder + meeting_recording_attribution_chain + speaker_consent_flag + meeting_recording_ip_flag "
"+ source_copyleft_flag + source_license_collision_flag + downstream_model_derivative_use + "
"compliance_metadata_retention_until - unique Fireflies lane because 4M+ users generate meeting-recording "
"training-data with implied-consent but no explicit-per-record-license, and the EU AI Act Aug 2026 GPAI "
"enforcement deadline propagates to every Fireflies customer), (3) Fireflies speaker-diarization + "
"sentiment-analysis + talk-time + topic-detection decision-tree per EU AI Act Annex III 4 high-risk + "
"EU AI Act Art. 14 human-oversight + GDPR Art. 22 automated-decision-making + Illinois BIPA + Texas CUBI "
"+ Washington biometric-privacy-law + California CCPA/CPRA (11-column per-meeting-recording join-table linking "
"meeting_recording_id + speaker_diarization_segment_hash + sentiment_score_per_segment + talk_time_per_speaker "
"+ topic_detection_classification + speaker_consent_capture_timestamp + ai_summary_classification + "
"ai_action_item_classification + downstream_crm_state_change_hash + compliance_metadata_retention_until + "
"audio_recording_storage_encryption_hash - unique Fireflies lane because the speaker-diarization + "
"sentiment-analysis + talk-time surfaces expose biometric-identifier + voice-print data subject to BIPA "
"+ CUBI + GDPR Art. 9 when meeting-recordings cross into employment-decision or hiring-screening context), "
"(4) Fireflies Knowledge-Base + Apps-Marketplace isolation-evidence per SOC 2 CC6.1 + GDPR Art. 28 + HIPAA "
"+ EU AI Act Art. 10 + BIPA (per-tenant isolation-test-result + per-tenant CMK/BYOK optionality + "
"per-meeting-no-leakage-evidence + per-Knowledge-Base-no-cross-tenant-leakage + per-Apps-Marketplace-vendor-isolation + "
"completion-of-deletion timestamp + per-customer-no-leakage-evidence for Nasdaq + Uber + Shopify + Mayo Clinic + "
"Stanford multi-tenant Fireflies Cloud - unique Fireflies lane because the Knowledge-Base + Apps-Marketplace "
"+ 50+ third-party-integrations surface is a unique third-party-supply-chain audit-target that Gong doesn't "
"ship in the same form), (5) EU AI Act Annex III 4 high-risk classification for Fireflies customers using "
"AskFred + AI-summary + AI-action-item in employment-decision + hiring-screening + performance-review lane "
"per Art. 6 + 14 + 27 + 43 + 72 + Art. 50 transparency-obligation + 12-column end-to-end Fireflies-meeting-to-high-risk-decision "
"reconstruction linking fireflies_meeting_id + meeting_recording_id + speaker_diarization_hash + ai_summary_hash "
"+ ai_action_item_hash + askfred_qa_response_hash + downstream_employment_decision_hash + "
"high_risk_jurisdiction_classification + employee_id_hash + cost_usd_at_meeting + latency_ms + "
"regulatory_retain_until - unique Fireflies lane because AskFred + AI-summary + AI-action-item are "
"the natural EU AI Act Art. 50 transparency-obligation surface AND the auditor will specifically probe the "
"per-meeting + per-decision provenance because every employment-impacting decision must cite its source-meeting "
"+ source-AI-summary + source-AI-action-item per Art. 50). hello@fireflies.ai verified live as the canonical "
"ai_sales_ai meeting-notes + conversation-intelligence + AskFred-AI-assistant + Knowledge-Base audit-target "
"inbound channel (consistent with the public B2B-SaaS-canonical-inbox pattern used at Persana 221 + "
"Artisan 222 + Lavender 117 + Gong 167 - the ai_sales_ai vertical uses hello@ or privacy@ for the "
"GDPR-DPA + SOC 2 + EU-AI-Act inbound)."
)

with open(path, 'a', newline='', encoding='utf-8') as f:
    w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    w.writerow([168, "Fireflies.ai", "@firefliesai", "hello@fireflies.ai", "ai_sales_ai", 1, "248_fireflies.md", tier_reason])

print("OK lead 168 (Fireflies.ai) appended")