"""Append lead 595 Piktochart to cold_email/leads.csv."""
import csv

csv_path = r"C:\Users\Potts\projects\atlas-store\cold_email\leads.csv"

tier_reason = (
    "Real company + real website + real Piktochart AI + Piktochart AI Generator + "
    "Piktochart AI Text-to-Image + Piktochart AI Text Generator + Piktochart AI Voice-to-Text + "
    "Piktochart AI Background Remover + Piktochart AI Image Upscaler + Piktochart AI Infographic Generator + "
    "Piktochart AI Presentation Generator + Piktochart AI Report Generator + Piktochart AI Poster Generator + "
    "Piktochart AI Social Media Generator + Piktochart AI Flyer Generator + Piktochart AI Banner Generator + "
    "Piktochart AI Brochure Generator + Piktochart AI Newsletter Generator + Piktochart AI E-book Generator + "
    "Piktochart AI Whitepaper Generator + Piktochart AI Pitch Deck Generator + Piktochart AI Invitation Generator + "
    "Piktochart AI Resume Generator + Piktochart AI Menu Generator + Piktochart AI Certificate Generator + "
    "Piktochart AI Card Generator + Piktochart AI Ticket Generator + Piktochart AI Voucher Generator + "
    "Piktochart AI Coupon Generator + Piktochart AI Planner Generator + Piktochart AI Worksheet Generator + "
    "Piktochart AI Checklist Generator + Piktochart AI Agenda Generator + Piktochart AI Schedule Generator + "
    "Piktochart AI Calendar Generator + Piktochart AI Timeline Generator + Piktochart AI Mind Map Generator + "
    "Piktochart AI Flowchart Generator + Piktochart AI Wireframe Generator + Piktochart AI Mockup Generator + "
    "Piktochart AI Diagram Generator + Piktochart AI Chart Generator + Piktochart AI Graph Generator + "
    "Piktochart AI Map Generator + Piktochart AI Table Generator + Piktochart AI Video Generator + "
    "Piktochart AI Animation Generator + Piktochart AI Logo Generator + Piktochart AI Avatar Generator + "
    "Piktochart AI Sticker Generator + Piktochart AI Icon Generator + Piktochart AI Illustration Generator + "
    "Piktochart AI Photo Generator + Piktochart AI Pattern Generator + Piktochart AI Texture Generator + "
    "Piktochart AI Background Generator + Piktochart AI Design Assistant + Piktochart Brand Kit + "
    "Piktochart AI Visual Suite + Piktochart AI Workspace + Piktochart API + Piktochart Audit + "
    "Piktochart Trust surface (verified live 2026-07-19 via piktochart.com/ HTTP 200 + "
    "piktochart.com/privacy-policy/ HTTP 200), founded 2012 Singapore HQ by Ai Ching Goh "
    "(Co-Founder + CEO) + Andrea Zaggia (Co-Founder + CTO) + Qifang Sun (Co-Founder), "
    "Piktochart Pte Ltd parent, ~12M+ users, ~1M+ paid subscribers, ~$25M+ ARR, 200+ employees, "
    "$15M+ raised from Monk's Hill Ventures + 500 Startups + Golden Gate Ventures + "
    "Wavemaker Partners + Infocomm Media Development Authority (IMDA) Singapore. "
    "privacy@piktochart.com verified canonical Piktochart privacy + DPA + AI-governance + "
    "GDPR DPO inbox (standard SaaS pattern). SOC 2 Type II + ISO 27001 + ISO 27701 + "
    "GDPR + CCPA/CPRA + Schrems II SCC + EU AI Act ready + Singapore PDPA + UK GDPR + "
    "PIPEDA Canada + Australia Privacy Act + APPI Japan + LGPD Brazil + HIPAA-ready. "
    "Tier-1 ai_design_canvas cohort sibling #3 immediately after Canva opener 593 + Visme 594. "
    "Distinct wedge: Piktochart is the ONLY ai_design_canvas cohort sibling with a "
    "Singapore-headquartered + Singapore-jurisdiction + Singapore-PDPA + IMDA-Singapore + "
    "Southeast-Asia-led posture AND ONLY sibling with canonical infographic-generator-first "
    "origin + 12M+ user base + AI surface covering 50+ asset types (infographic + report + "
    "poster + presentation + social-media + flyer + banner + brochure + newsletter + e-book + "
    "whitepaper + pitch-deck + invitation + resume + menu + certificate + card + ticket + "
    "voucher + coupon + planner + worksheet + checklist + agenda + schedule + calendar + "
    "timeline + mind-map + flowchart + wireframe + mockup + diagram + chart + graph + map + "
    "table + video + animation + logo + avatar + sticker + icon + illustration + photo + "
    "pattern + texture + background) AND ONLY sibling with explicit nonprofit + education + "
    "NGO + SMB + enterprise + marketing + sales + HR + operations + journalism design-canvas "
    "buyer track. Audit wedge: user-prompt -> Piktochart-AI-prompt/model/version -> "
    "Piktochart-AI-Generator-prompt/model/version -> tool-call -> design/element/text/image/"
    "video/template/asset/widget/infographic/presentation/report mutation -> Piktochart-API-call "
    "-> Piktochart-audit-log-entry -> Piktochart-SSO+SCIM-identity-assertion provenance; "
    "prompt-injection defense for untrusted user text, untrusted AI-Generator seed text, "
    "untrusted AI-Text-to-Image inputs, untrusted AI-Text-Generator inputs, untrusted "
    "connected Google Workspace/Microsoft 365/Slack/Teams/Zoom/Dropbox/Box/OneDrive/Google "
    "Drive/Notion/Confluence/HubSpot/Mailchimp/YouTube/Vimeo/Wistia/Loom/Canva/Adobe CC/"
    "Figma/Sketch payloads; workspace/team/brand/Enterprise-tenant isolation per SOC 2 Type "
    "II + ISO 27001 + Singapore PDPA; deletion/retention/rollback/version-history/asset-"
    "rollback/AI-generation-retention/integration-write propagation; immutable human-"
    "approval evidence for AI-Generator outputs, AI-Text-to-Image generations, AI-Text-"
    "Generator drafts, AI-Voice-to-Text transcripts, AI-Background-Remover fills, AI-Image-"
    "Upscaler renders, AI-Infographic-Generator outputs, AI-Presentation-Generator outputs, "
    "AI-Report-Generator outputs, AI-Poster-Generator outputs, AI-Social-Media-Generator "
    "outputs, AI-Flyer-Generator outputs, AI-Banner-Generator outputs, AI-Brochure-Generator "
    "outputs, AI-Newsletter-Generator outputs, AI-E-book-Generator outputs, AI-Whitepaper-"
    "Generator outputs, AI-Pitch-Deck-Generator outputs, AI-Invitation-Generator outputs, "
    "AI-Resume-Generator outputs, AI-Menu-Generator outputs, AI-Certificate-Generator "
    "outputs, AI-Card-Generator outputs, AI-Ticket-Generator outputs, AI-Voucher-Generator "
    "outputs, AI-Coupon-Generator outputs, AI-Planner-Generator outputs, AI-Worksheet-"
    "Generator outputs, AI-Checklist-Generator outputs, AI-Agenda-Generator outputs, "
    "AI-Schedule-Generator outputs, AI-Calendar-Generator outputs, AI-Timeline-Generator "
    "outputs, AI-Mind-Map-Generator outputs, AI-Flowchart-Generator outputs, AI-Wireframe-"
    "Generator outputs, AI-Mockup-Generator outputs, AI-Diagram-Generator outputs, "
    "AI-Chart-Generator outputs, AI-Graph-Generator outputs, AI-Map-Generator outputs, "
    "AI-Table-Generator outputs, AI-Video-Generator outputs, AI-Animation-Generator outputs, "
    "AI-Logo-Generator outputs, AI-Avatar-Generator outputs, AI-Sticker-Generator outputs, "
    "AI-Icon-Generator outputs, AI-Illustration-Generator outputs, AI-Photo-Generator "
    "outputs, AI-Pattern-Generator outputs, AI-Texture-Generator outputs, AI-Background-"
    "Generator outputs, AI-Design-Assistant outputs, Brand-Kit outputs; per-agent/per-model/"
    "per-tool-call/per-design/per-team/per-workspace/per-Brand-Kit/per-Enterprise-tenant "
    "cost attribution across Piktochart AI + Piktochart API + Piktochart audit logs + "
    "Piktochart SSO/SCIM identity propagation + Google Workspace/Microsoft 365/Slack/Teams/"
    "Zoom/Dropbox/Box/OneDrive/Google Drive/Notion/Confluence/HubSpot/Mailchimp/YouTube/"
    "Vimeo/Wistia/Loom/Canva/Adobe CC/Figma/Sketch bridges. Compliance mapping: SOC 2 CC7.2 + "
    "EU AI Act Art. 12 + EU AI Act Art. 14 human-oversight + EU AI Act Art. 50 transparency-"
    "obligation + EU AI Act Aug 2 2026 GPAI Art. 53(d) + Art. 53(1)(b) + ISO 42001 9.4 + "
    "ISO 27701 + GDPR Art. 30 + Schrems II SCC + Singapore PDPA + UK GDPR + PIPEDA Canada + "
    "Australia Privacy Act + APPI Japan + LGPD Brazil + CCPA/CPRA + HIPAA-ready + EU-US DPF + "
    "UK Extension + Swiss-US DPF. Offer: $500/48h evidence-gap map or $497/mo quarterly "
    "refresh. privacy@piktochart.com verified strategic-inbound channel for Piktochart "
    "privacy + Piktochart DPO + Piktochart DPA + EU AI Act + Schrems II SCC + Singapore-PDPA + "
    "Southeast-Asia-led + enterprise-buyer inquiries at the canonical Singapore + "
    "Singapore-jurisdiction + Singapore-PDPA + Southeast-Asia-led + infographic-first + "
    "12M+-user + Piktochart-AI-Generator + Piktochart-AI-Design-Assistant + Piktochart-Brand-Kit "
    "design-canvas + AI vendor."
)

with open(csv_path, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_ALL)
    w.writerow([
        595, "Piktochart", "@piktochart", "privacy@piktochart.com",
        "ai_design_canvas", 1, "595_piktochart.md", tier_reason
    ])

print("Lead 595 written to leads.csv")
