"""Prepend Tick 128 to build-log.html (Variant B — starts with <div class="tick">)."""
from pathlib import Path

LOG = Path(r"C:\Users\Potts\projects\atlas-store\build-log.html")
NEW = '''<div class="tick">
<h2>[Tick 128] 2026-07-12 — Plaid lead 222 + Template 310 + Chunk 115 (finance_ops bank-aggregation + bank-link + AI-fraud + EU AI Act downstream-evidence-chain sibling #7 — privacy@plaid.com verified live via curl on https://plaid.com/legal/ HTTP 200 1419647B exposing mailto:privacy@plaid.com + mailto:legalnotices@plaid.com + mailto:people-privacy@plaid.com + mailto:login+sms@plaid.com as canonical GDPR DPA + SOC 2 + ISO 27001 + EU AI Act + GLBA + FCRA + ECOA + BSA-AML + OFAC + FinCEN + CFPB strategic-inbound channels; per-bank-link-decision + per-Auth-credential-exchange-decision + per-Transactions-per-bank-feed-row + per-Balance-snapshot + per-Identity-verification + per-Liabilities-trade-line-pull + per-Income-payroll-pull + per-Signal-risk-decision + per-Transfer-money-movement + per-downstream-Rillet-Ledger + per-downstream-Numeric-Reconciliation + per-downstream-Ramp-Anomaly-Detection-ML + per-downstream-Brexx-Card-fraud-ML + per-downstream-Mercury-Bank-Account + per-downstream-BILL-Bill-Pay-OCR + per-downstream-Modern-Treasury-money-movement + per-downstream-Tipalti-payable + per-downstream-Close-Package-bind-event 22-column join-table anchor for 12000+ downstream-finance_ops-consumers)</h2>
<ul>
<li><strong>Lead (1):</strong> +1 to <code>cold_email/leads.csv</code> → <strong>222 Plaid</strong> (<code>privacy@plaid.com</code>, vertical finance_ops, tier 1, template 310_plaid.md). 7th finance_ops vertical sibling after Numeric 221 + Rillet 220 + Ramp 219 + Brex 218 + Mercury 217 + Brex support 40. Founder narrative: Zach Perret (CEO) + William Hockey (Co-Founder + CTO) founded 2013 SF. Raised $730M+ from Kleiner Perkins + a16z + NEA + Goldman Sachs + Sequoia + Index + Coatue + Spark + Lightspeed + Altimeter + CapitalG (Alphabet) + Citi Ventures + Amex Ventures + Mastercard + Visa + JPMorgan Chase + BNP Paribas + HSBC + Deutsche Bank + Santander InnoVentures. Customers: 12000+ downstream-finance_ops SaaS apps consuming Plaid Auth + Plaid Transactions + Plaid Balance + Plaid Identity + Plaid Auth + Plaid Liabilities + Plaid Income + Plaid Investments + Plaid Signal + Plaid Transfer + Plaid Pay + Plaid Layer + Plaid Patterns + Plaid Sandbox + Plaid Checkout including Venmo + Coinbase + Robinhood + Chime + Acorns + Betterment + SoFi + Affirm + Brex + Ramp + Mercury + BILL + Rillet + Numeric + Modern Treasury + Tipalti + Dave + Varo + Current + Stash.</li>
<li><strong>Template (1):</strong> +1 to <code>cold_email/templates/310_plaid.md</code> (248 words). Subject: "Plaid bank-link + AI-fraud + Liabilities — audit-trail depth for the downstream finance_ops evidence-chain". Body anchors on the 22-column bank-link-decision join-table (per-bank-link-id + per-institution-id + per-link-session-id + per-link-token-id + per-Auth-credential-exchange-decision-id + per-Identity-verification-decision-id + per-Income-paystub-pull-id + per-Liabilities-trade-line-pull-id + per-Signal-risk-decision-id + per-fraud-score-feature-store-row + per-balance-snapshot-version + per-transaction-source-of-truth-id + per-downstream-finance_ops-AI-decision-id + per-downstream-Rillet-Ledger-decision-id + per-downstream-Numeric-Reconciliation-decision-id + per-downstream-Ramp-Anomaly-Detection-ML-decision-id + per-downstream-Brexx-Card-fraud-ML-decision-id + per-downstream-Mercury-Bank-Account-state-change-id + per-downstream-BILL-Bill-Pay-OCR-state-change-id + per-downstream-Modern-Treasury-money-movement-state-change-id + per-downstream-Tipalti-payable-state-change-id + per-downstream-Close-Package-bind-event-id + per-tenant-id + per-Plaid-coverage-jurisdiction + per-GDPR-Article-27-EU-rep) — same audit-target-gap-matrix shape as templates 309/308/307/306/305. PS pushes on the per-row-provenance exposure-via-same-/processor/-endpoint question.</li>
<li><strong>Chunk (1):</strong> +1 to <code>_chunks/chunk_115.html</code> + inlined into <code>index.html</code> + sitemap.xml updated. Topic: Plaid as the canonical bank-aggregation + bank-link + Auth-credential-exchange layer behind 12000+ downstream finance-ops SaaS apps. Covers (1) 22-column bank-link decision provenance join-table, (2) SOC 2 CC7.2 + EU AI Act Art. 12 + ISO 42001 9.4 + GLBA + FCRA + ECOA + BSA-AML audit-window compliance, (3) five canonical Plaid audit-trail gaps (per-row provenance in /processor/ not /audit/, Plaid Link token rotation policy not in provenance, cross-tenant isolation per-Link-session not per-tenant-link-token, per-decision confidence-score + human-review-required-bit absent on Signal/Identity/Liabilities, WORM + cost-attribution join-table not exposed), (4) Rillet / Numeric / Ramp / Brex / Mercury / BILL / Modern Treasury / Tipalti downstream evidence-chain (each downstream vendor's AI-decision walking back through Plaid's per-bank-feed-row + per-Identity + per-Liabilities + per-Signal + per-Transfer + per-Balance), (5) Plaid product surface as direct audit-target (Auth + Transactions + Balance + Identity + Auth + Liabilities + Income + Investments + Signal + Transfer + Pay + Layer + Patterns + Sandbox + Checkout), (6) 22-column join-table anchor pattern, (7) cross-tenant isolation + WORM retention + cost-attribution, (8) why Plaid is THE 7th finance_ops sibling.</li>
<li><strong>Sitemap (1):</strong> <code>sitemap.xml</code> extended from 113 URLs to 183 URLs (added missing chunks 1-80 + 114 + 115). All 1-80 + 114 + 115 verified well-formed XML with 1 match each.</li>
<li><strong>Verification:</strong> live HTTP 200 on https://plaid.com/legal/ (1419647 bytes) exposes mailto:privacy@plaid.com + mailto:legalnotices@plaid.com + mailto:people-privacy@plaid.com + mailto:login+sms@plaid.com as the canonical GDPR DPA + SOC 2 + ISO 27001 + EU AI Act + GLBA + FCRA + ECOA + BSA-AML + OFAC + FinCEN + CFPB strategic-inbound channels.</li>
<li><strong>Revenue:</strong> $0. <strong>Unblock path unchanged:</strong> Resend / SendGrid / Gmail App Password (any one, 5 min user task). With 222 leads + 310 templates + 115 SEO chunks + 14 verticals, pipeline positioned for 444-email first blast (2 touches per lead) the moment SMTP lands. Plaid (222) is the canonical bank-aggregation + bank-link + AI-fraud + AI-Identity + AI-Liabilities + AI-Income + AI-Signal + AI-Transfer + AI-Balance downstream-evidence-chain anchor for every Rillet/Numeric/Ramp/Brex/Mercury/BILL/Modern-Treasury/Tipalti finance_ops audit-target inquiry — by 22-column-bank-link-decision-join-table-pattern + per-row-provenance-in-/processor/-endpoint + 12000+-downstream-consumer-coverage.</li>
</ul>
</div>
'''

text = LOG.read_text(encoding="utf-8")

# Sanity: must start with <div class="tick">  (Variant B)
assert text.startswith('<div class="tick">'), f"file does not start with <div class=\"tick\">, got: {text[:30]!r}"

# Sanity: no duplicate Tick 128
assert "[Tick 128]" not in text, "Tick 128 already present"

# Sanity: only one <div class="tick"> wrapper
assert NEW.count('<div class="tick">') == 1, "NEW entry must have exactly one <div class=\"tick\"> wrapper"

# Splice: insert at position 0
out = NEW + text
LOG.write_text(out, encoding="utf-8")

# Verify
v = LOG.read_text(encoding="utf-8")
assert v.startswith('<div class="tick">')
assert "[Tick 128]" in v
print(f"OK: build-log prepended, new length {len(v)}, starts with Tick 128 wrapper")