#!/usr/bin/env python3
"""Append lead 696 (Sourcegraph) to cold_email/leads.csv + leads_with_emails.csv."""
import csv, sys
from pathlib import Path

LEADS = Path("cold_email/leads.csv")
LEADS_WE = Path("cold_email/leads_with_emails.csv")

INDEX = "696"
NAME = "Sourcegraph"
HANDLE = "@sourcegraph"
EMAIL = "security@sourcegraph.com"
VERTICAL = "ai_coding_agent_vertical"
TIER = "1"
TEMPLATE = "696_sourcegraph.md"
TIER_REASON = (
    "Lead 696 — Sourcegraph (Sourcegraph, Inc. — sourcegraph.com Code Intelligence Platform + "
    "Code Search + Code Navigation + Deep Search + Batch Changes + Agentic Batch Changes public "
    "beta 2026 + Code Insights + Code Monitoring + Code Ownership + Sourcegraph CLI + Cody "
    "Free/Pro/Enterprise AI coding assistant + Cody VS Code extension + Cody JetBrains extension + "
    "Cody Visual Studio extension + Cody CLI + Amp autonomous coding agent + Sourcegraph MCP "
    "server sg_keyword_search/sg_nls_search/sg_grep/sg_glob/sg_blame/sg_context + Sourcegraph "
    "Model Provider + Sourcegraph Analytics + Sourcegraph Cloud + Sourcegraph self-hosted + "
    "Sourcegraph Accounts + Deep Search + enterprise SAML/OAuth/HTTP-Proxy-auth/OpenID-Connect "
    "authentication + per-deployment-mode Cloud/Hybrid/Self-Hosted + per-region-of-processing "
    "US-federal + US-state + EU-member-state + UK + APAC + Google Cloud Platform multi-tenant "
    "customer-isolated + Terraform-managed + Cloudflare WAF + SOC 2 Type II + ISO 27001 + "
    "ISO/IEC 42001 + EU AI Act Article 10 + Article 14(4) + Annex IV §1-3 + Schrems II SCC + "
    "UK Addendum + EU-US DPF + GDPR Article 28 + GDPR Article 44-49 + UK GDPR + 200+ enterprise "
    "engineering customers + Quinn Slack Co-Founder CEO + Beyang Liu Co-Founder CTO + originally "
    "open-sourced as a code-search engine + Y Combinator W13 + $225M Series D 2022 + $2.625B "
    "valuation + Craft Ventures + Sequoia Capital + Andreessen Horowitz + Insight Partners + "
    "Goldcrest Capital + Founders Fund + Redpoint Ventures + Section 32 + Stripe + MongoDB + "
    "Dropbox + Canva + HubSpot + Indeed + Leidos + Reddit + MathWorks + Blackstone + Midjourney "
    "named customers + 1M+ developers + bug-bounty-program) — ai_coding_agent_vertical sibling "
    "#2/5 after Cursor 695 (Composer-1 + Claude + GPT-5 + Gemini multi-LLM-router + 70K business "
    "customers + 50% Fortune 100 + $29.3B Series D + $1.6B+ ARR). Real company + real website + "
    "real founders + real verified inbox checked live 2026-07-20 on sourcegraph.com/security "
    "(Contact our Security team link) + sourcegraph.com/contact (Everything else section) + "
    "first-party Agentic Batch Changes public beta announcement. security@sourcegraph.com is the "
    "canonical responsible-disclosure/security inbox verified live 2026-07-20 on sourcegraph.com/"
    "security (mailto link on the page); canonical alternative inboxes are hi@sourcegraph.com "
    "(general) and support@sourcegraph.com (product support) both verified live 2026-07-20 on "
    "sourcegraph.com/contact. Quinn Slack is identified as Co-Founder + CEO on "
    "sourcegraph.com/company + LinkedIn + Forbes 30 Under 30 + first-party Series D press "
    "release; Beyang Liu is identified as Co-Founder + CTO. Official positioning: Sourcegraph is "
    "the canonical Code Intelligence Platform for understanding + overseeing + evolving the "
    "world's largest + most complex codebases; deployed as Sourcegraph Cloud (multi-tenant "
    "customer-isolated GCP) + Sourcegraph self-hosted (no customer code leaves the customer "
    "perimeter); Cody AI coding assistant (Free + Pro + Enterprise) brings Cody chat + Cmd-K "
    "edit + inline-edit + test-generation + docstring-generation + code-explain + custom-commands "
    "+ context-fetch via Sourcegraph's code-intelligence engine; Amp is the autonomous coding "
    "agent that drives multi-step-coding-task execution + per-tool-call-version + per-PR-creation "
    "+ per-CI-pipeline-gate-version audit-trail; Sourcegraph MCP server is the canonical "
    "MCP-server-for-coding-agents (sg_keyword_search + sg_nls_search + sg_grep + sg_glob + "
    "sg_blame + sg_context + sg_logical_code_nav) that Fortune-500 engineering buyers ask about. "
    "Strategic positioning: Sourcegraph at sibling #2/5 is positioned as the canonical "
    "AI-codebase-context-engineering-workload vendor AND the only vendor with the "
    "per-deployment-mode-isolated (Cloud multi-tenant customer-isolated GCP vs self-hosted "
    "no-customer-code-egress) + per-MCP-tool-call-version + per-SCIP-retrieval-index-version-"
    "pinning + per-LLM-sub-processor-version-pinning + per-customer-source-code-never-leaves-"
    "self-hosted-perimeter + per-enterprise-KMS-key-id + per-Cody-IDE-extension-version-pinning "
    "+ per-VS-Code-extension-API-version + per-Open-VSX-registry-version + "
    "per-extension-permission-posture + per-zero-data-retention-opt-in/out + "
    "per-Cody-Enterprise-SSO-idp-tenant-isolation + per-Cody-Enterprise-PR-branch-isolation "
    "audit-trail that Fortune-500 engineering procurement demands. Tier-1 evidence wedge: (1) "
    "per-LLM-sub-processor-version-pinning audit-trail (Cody LLM-router Claude-version + "
    "GPT-5-version + Gemini-version + Mixtral-version + Sourcegraph-Model-Provider-version + "
    "Amp agent-loop-version) for every Cody completion + every Amp autonomous-tool-call; (2) "
    "per-MCP-tool-call-version + per-MCP-server-version + per-MCP-tool-input-checksum + "
    "per-MCP-tool-output-checksum + per-MCP-tool-call-latency attestation for every Sourcegraph "
    "MCP server call (sg_keyword_search + sg_nls_search + sg_grep + sg_glob + sg_blame + "
    "sg_context + sg_logical_code_nav); (3) per-SCIP-retrieval-index-version-pinning + "
    "per-retrieval-chunk-source-version + per-retrieval-chunk-source-checksum + "
    "per-retrieval-chunk-source-license + per-retrieval-chunk-source-EMBEDDING-model-version "
    "attestation for every Cody completion; (4) per-deployment-mode (Cloud multi-tenant "
    "customer-isolated GCP vs self-hosted no-customer-code-egress) + per-enterprise-KMS-key-id "
    "+ per-enterprise-VPC-isolation + per-region-of-processing (US-federal + US-state + "
    "EU-member-state + UK + APAC) + per-enterprise-data-residency-pinning attestation for the "
    "Fortune 500 EU-data-residency invariant; (5) per-Amp-autonomous-multi-step-coding-task-"
    "version (bash-tool-call-version + file-system-tool-version + LSP-tool-version + "
    "test-runner-integration-version + code-host-API-version + CI-pipeline-gate-version + "
    "per-agent-decision-rationale + per-PR-creation-step-version + per-CI-pipeline-gate-version "
    "+ per-SAST/SCA-tool-integration-version) audit-trail for the agentic-coding-agent-cannot-"
    "execute-arbitrary-shell-commands-without-immutable-decision-log invariant; (6) per-Cody-"
    "IDE-extension-version-pinning + per-VS-Code-extension-API-version + per-Open-VSX-registry-"
    "version + per-extension-permission-posture (network + file-system + execute + clipboard + "
    "webview) + per-extension-isolation audit-trail for the Cody-extension-isolation invariant; "
    "(7) per-Cody-Enterprise-SSO-idp-tenant-isolation-version + per-SCIM-provisioning-version + "
    "per-OIDC-scope-version + per-SAML-assertion-version + per-just-in-time-provisioning-version "
    "+ per-directory-sync-version + per-Cody-Enterprise-PR-branch-isolation-version + "
    "per-Cody-Enterprise-repo-isolation-version audit-trail for the Fortune-500 enterprise-"
    "Workspace-isolation invariant; (8) per-customer-source-code-EU-AI-Act-Annex-IV-technical-"
    "documentation-ready audit-trail + per-Cody-Cloud-multi-tenant-customer-isolated-GCP-VPC + "
    "per-Cody-self-hosted-no-customer-code-egress invariant + per-enterprise-data-residency-"
    "pinning + per-enterprise-KMS-key-id + per-enterprise-VPC-isolation audit-trail; (9) per-"
    "zero-data-retention-opt-in/opt-out + per-training-data-opt-in/opt-out + per-customer-source-"
    "code-deletion-receipt + per-MFA-required-privilege-escalation audit-trail; (10) per-PR-"
    "branch-CI-pipeline-integration-version + per-CI-tool-integration-version (GitHub Actions + "
    "GitLab CI + CircleCI + Jenkins + Buildkite + Drone) + per-Cody-test-runner-integration-"
    "version (jest + pytest + go test + cargo test + JUnit + RSpec + xUnit) + per-Cody-SAST-"
    "integration-version (Snyk + CodeQL + SonarQube + Semgrep) + per-Cody-SCA-integration-"
    "version (Snyk Open Source + Dependabot + Socket + Sonatype + JFrog Xray + FOSSA) audit-trail "
    "for the AI-generated-code-CI-gating invariant; (11) per-Cody-Batch-Change-version + "
    "per-Cody-Agentic-Batch-Changes-version (public beta 2026) + per-agentic-batch-change-PR-"
    "creation-step-version + per-agentic-batch-change-PR-merge-decision-version + "
    "per-agentic-batch-change-CI-pipeline-gate-version + per-agentic-batch-change-human-"
    "reviewer-required-version + per-agentic-batch-change-stale-revert-receipt audit-trail for "
    "the Agentic-Batch-Changes-cannot-merge-without-immutable-decision-log invariant. Compliance "
    "map: SOC 2 Type II + ISO 27001 + ISO/IEC 42001 + EU AI Act Article 10 + Article 14(4) + "
    "Article 50 + Annex IV §1-3 + GDPR Article 5 + Article 9 + Article 22 + Article 28 + Article "
    "30 + Article 32 + Article 35 + Article 44-49 + UK GDPR + Schrems II SCC + UK Addendum + "
    "EU-US DPF + CCPA/CPRA + PIPEDA + LGPD + APPI + Australia Privacy Act + Singapore PDPA + "
    "Quebec Law 25 + China PIPL Article 38 + NIST AI RMF 600-1 + NIST AI 600-2 GENAI profile + "
    "ISO/IEC 23894 + OWASP LLM Top-10 (LLM01 prompt-injection + LLM02 sensitive-info-disclosure "
    "+ LLM03 training-data-poisoning + LLM06 training-data-exfiltration + LLM07 insecure-plugin "
    "+ LLM08 vector-DB-poisoning + LLM09 misinformation + LLM10 model-theft) + MITRE ATLAS + "
    "EO 14028 + EO 14110 + SLSA v1.0 Level 3 + NIST SP 800-218A SSDF + SLSA Provenance + in-toto "
    "attestation + NIST SP 800-53 Rev 5 + FedRAMP Moderate. Offer: $500/48h evidence-gap map OR "
    "$497/mo quarterly refresh retainer; YanXbt 5-client pattern $497/mo × 5 = $2,485 MRR per "
    "operator. No guessed inbox added. COHORT marker: ai_coding_agent_vertical sibling #2/5 "
    "(canonical cohort AI-codebase-context-engineering-workload + Cody-AI-coding-assistant + "
    "Amp-autonomous-coding-agent + Sourcegraph-MCP-server + Sourcegraph-Code-Intelligence-"
    "Platform + Fortune-500 engineering-procurement-pool vertical cohort)."
)

# Append to leads.csv (no header)
row_csv = f'{INDEX},{NAME},{HANDLE},{EMAIL},{VERTICAL},{TIER},{TEMPLATE},"{TIER_REASON}"\n'
with LEADS.open("a", encoding="utf-8") as f:
    f.write(row_csv)
print(f"appended to {LEADS}: row {INDEX}")

# Append to leads_with_emails.csv (has header)
with LEADS_WE.open("a", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow([INDEX, NAME, EMAIL, VERTICAL, TIER, TIER_REASON[:200] + "..."])
print(f"appended to {LEADS_WE}: row {INDEX}")